name: Build Android APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
      - name: Generate Gradle wrapper
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.7
          arguments: wrapper
      - name: Build debug APK
        # Secrets are optional; you can input token/versions inside the app Settings after install
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
          MODEL_PREVIEW_VERSION: ${{ secrets.MODEL_PREVIEW_VERSION }}
          MODEL_FINAL_VERSION: ${{ secrets.MODEL_FINAL_VERSION }}
        run: ./gradlew assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
